### ISSUE TITLE
Add go* repos to listing?

### ISSUE THREAD

**Issue by decentral1se** [ssbc/.github#4]
Can then https://github.com/orgs/ssbc/repositories?language=go&type=all repos be added? Missing afaiu

**Comment by staltz** [comment]
The go repos are included, see the first hundreds of lines in the CI job: https://github.com/ssbc/.github/actions/runs/3358134766/jobs/5564675691

I can spot e.g. go-muxrpc, go-ssb-refs, go-ssb-room, go-secretstream, go-ssb, go-luigi...
